services:
  - type: web
    name: multi-user-expense-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false # Set this in the Render Dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false # Set this in the Render Dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false # Set this in the Render Dashboard
      - key: PYTHON_VERSION
        value: 3.12.2
